spring:
  application:
    # 项目名
    name: user-center
  datasource:
    # driver-class-name: org.h2.Driver 官方的demo使用的是h2数据库，这里使用mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost:3306/hcj
    username: root
    password: 12345678
  session:
    timeout: 86400
server:
  # 端口号
  port: 8080
mybatis-plus:
  # 解决mybatis-plus默认将驼峰转换为下划线
  configuration:
    map-underscore-to-camel-case: false
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)